# Check `docs/pipeline.md` to get info about this file

resources:
- name: hellokite-repository
  type: git
  source:
    uri: https://github.com/helios-technologies/hellokite
    branch: master

- name: hellokite-image
  type: docker-image
  source:
    repository: gcr.io/helios-devel/hellokite
    username: {{docker_username}}
    password: {{docker_password}}

jobs:
- name: hellokite
  serial: true
  plan:
  - get: hellokite-repository
    trigger: true
  - put: hellokite-image
    params:
      build: hellokite-repository
